# Generated by Django 5.0.6 on 2024-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_date_added_inventoryitem_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
